#include "ADC_INTERFACE.h"

void ADC_INIT(void)
{
    #if CHANNEL== CHANNEL_0
    CLR_BIT(ADMUX_REG, MUX0);
    CLR_BIT(ADMUX_REG, MUX1);
    CLR_BIT(ADMUX_REG, MUX2);
    CLR_BIT(ADMUX_REG, MUX3);
    CLR_BIT(ADMUX_REG, MUX4);
    #elif CHANNEL== CHANNEL_1
    SET_BIT(ADMUX_REG, MUX0);
    CLR_BIT(ADMUX_REG, MUX1);
    CLR_BIT(ADMUX_REG, MUX2);
    CLR_BIT(ADMUX_REG, MUX3);
    CLR_BIT(ADMUX_REG, MUX4);
    #elif CHANNEL== CHANNEL_2
    CLR_BIT(ADMUX_REG, MUX0);
    SET_BIT(ADMUX_REG, MUX1);
    CLR_BIT(ADMUX_REG, MUX2);
    CLR_BIT(ADMUX_REG, MUX3);
    CLR_BIT(ADMUX_REG, MUX4);
    #elif CHANNEL == CHANNEL_3
    SET_BIT(ADMUX_REG, MUX0);
    SET_BIT(ADMUX_REG, MUX1);
    CLR_BIT(ADMUX_REG, MUX2);
    CLR_BIT(ADMUX_REG, MUX3);
    CLR_BIT(ADMUX_REG, MUX4);
    #elif CHANNEL == CHANNEL_4
    CLR_BIT(ADMUX_REG, MUX0);
    CLR_BIT(ADMUX_REG, MUX1);
    SET_BIT(ADMUX_REG, MUX2);
    CLR_BIT(ADMUX_REG, MUX3);
    CLR_BIT(ADMUX_REG, MUX4);
    #elif CHANNEL == CHANNEL_5
    SET_BIT(ADMUX_REG, MUX0);
    CLR_BIT(ADMUX_REG, MUX1);
    SET_BIT(ADMUX_REG, MUX2);
    CLR_BIT(ADMUX_REG, MUX3);
    CLR_BIT(ADMUX_REG, MUX4);
    #elif CHANNEL == CHANNEL_6
    CLR_BIT(ADMUX_REG, MUX0);
    SET_BIT(ADMUX_REG, MUX1);
    SET_BIT(ADMUX_REG, MUX2);
    CLR_BIT(ADMUX_REG, MUX3);
    CLR_BIT(ADMUX_REG, MUX4);
    #elif CHANNEL == CHANNEL_7
    SET_BIT(ADMUX_REG, MUX0);
    SET_BIT(ADMUX_REG, MUX1);
    SET_BIT(ADMUX_REG, MUX2);
    CLR_BIT(ADMUX_REG, MUX3);
    CLR_BIT(ADMUX_REG, MUX4);
    #endif

    #if DIV_FAC == DIV_FAC_2
    CLR_BIT(ADCSRA_REG, ADPS0);
    CLR_BIT(ADCSRA_REG, ADPS1);
    CLR_BIT(ADCSRA_REG, ADPS2);
    #elif dif_fac == DIV_FAC_4
    CLR_BIT(ADCSRA_REG, ADPS0);
    SET_BIT(ADCSRA_REG, ADPS1);
    CLR_BIT(ADCSRA_REG, ADPS2);
    #elif DIV_FAC == DIV_FAC_8
    SET_BIT(ADCSRA_REG, ADPS0);
    SET_BIT(ADCSRA_REG, ADPS1);
    CLR_BIT(ADCSRA_REG, ADPS2);
    #elif DIV_FAC == DIV_FAC_16
    CLR_BIT(ADCSRA_REG, ADPS0);
    CLR_BIT(ADCSRA_REG, ADPS1);
    SET_BIT(ADCSRA_REG, ADPS2);
    #elif DIV_FAC == DIV_FAC_32
    SET_BIT(ADCSRA_REG, ADPS0);
    CLR_BIT(ADCSRA_REG, ADPS1);
    SET_BIT(ADCSRA_REG, ADPS2);
    #elif DIV_FAC == DIV_FAC_64
    CLR_BIT(ADCSRA_REG, ADPS0);
    SET_BIT(ADCSRA_REG, ADPS1);
    SEt_BIT(ADCSRA_REG, ADPS2);
    #elif DIV_FAC == DIV_FAC_128
    SET_BIT(ADCSRA, ADPS0);
    SET_BIT(ADCSRA, ADPS1);
    SET_BIT(ADCSRA, ADPS2);
    #endif

    #if V_REF == AREF_Internal_Vref_turned_off
    CLR_BIT(ADMUX_REG, REFS0);
    CLR_BIT(ADMUX_REG, REFS1);
    #elif V_REF == AVCC_with_external_capacitor_at_AREF_pin
    SET_BIT(ADMUX_REG, REFS0);
    CLR_BIT(ADMUX_REG, REFS1);
    #elif V_REF == Reserved
    CLR_BIT(ADMUX_REG, REFS0);
    SET_BIT(ADMUX_REG, REFS1);
    #elif V_REF == Internal_2_56V_Voltage_Reference_with_external_capacitor_at_AREF_pin
    SET_BIT(ADMUX_REG, REFS0);
    SET_BIT(ADMUX_REG, REFS1);
    #endif
    #if ADJUST == ADC_LEFT
    SET_BIT(ADMUX_REG, ADLAR);
    #elif ADJUST == ADC_RIGHT
    CLR_BIT(ADMUX_REG, ADLAR);
    #endif
    #if AUTO_TRIGGER == TRUE
    #if TRIGGER_SRC == FREE_RUNNING
    CLR_BIT(SFIOR, ADTS0);
    CLR_BIT(SFIOR, ADTS1);
    CLR_BIT(SFIOR, ADTS2);
    #elif TRIGGER_SRC == ANALOG_CMOPARATOR
    SET_BIT(SFIOR, ADTS0);
    CLR_BIT(SFIOR, ADTS1);
    CLR_BIT(SFIOR, ADTS2);
    #elif TRIGGER_SRC == EXT_INT_REQ_0
    CLR_BIT(SFIOR, ADTS0);
    SET_BIT(SFIOR, ADTS1);
    CLR_BIT(SFIOR, ADTS2);
    #elif TRIGGER_SRC == TIMER_COUNTER0_COMPARE_MATCH
    SET_BIT(SFIOR, ADTS0);
    SET_BIT(SFIOR, ADTS1);
    CLR_BIT(SFIOR, ADTS2);
    #elif TRIGGER_SRC == TIMER_COUNTER0_OVF
    CLR_BIT(SFIOR, ADTS0);
    CLR_BIT(SFIOR, ADTS1);
    SET_BIT(SFIOR, ADTS2);
    #elif TRIGGER_SRC == TIMER_COUNTER1_COMPARE_MATCH_B
    SET_BIT(SFIOR, ADTS0);
    CLR_BIT(SFIOR, ADTS1);
    SET_BIT(SFIOR, ADTS2);
    #elif TRIGGER_SRC == TIMER_COUNTER1_OVF
    CLR_BIT(SFIOR, ADTS0);
    SET_BIT(SFIOR, ADTS1);
    SET_BIT(SFIOR, ADTS2);
    #elif TRIGGER_SRC == TIMER_COUNTER1_CAPTURE_EVENT
    SET_BIT(SFIOR, ADTS0);
    SET_BIT(SFIOR, ADTS1);
    SET_BIT(SFIOR, ADTS2);
    #endif
    SET_BIT(ADCSRA, ADATE); // to enable auto trigger
    #elif AUTO_TRIGGER == FALSE
    CLR_BIT(ADCSRA, ADATE);
    #endif
    
    SET_BIT(ADCSRA, ADEN); // to enable adc
}

Uint16 ADC_READ(void)
{
    SET_BIT(ADCSRA, ADSC); // to start the conversion
    while(GET_BIT(ADCSRA, ADIF) == 0); 
    return ADC_ADJUST;
}